#!/usr/bin/env bash
set -euo pipefail

echo "[Step 18] Enterprise Mobility Management (EMM) Deployment Guide"
echo ""

echo "[Step 18.1] EMM Overview"
echo "─────────────────────────"
echo ""
echo "EMM deployment allows you to distribute your app to enterprise customers"
echo "through managed Google Play. This is useful for B2B apps."
echo ""

echo "[Step 18.2] Prerequisites"
echo "────────────────────────"
echo ""
echo "  □ EMM console access (request from your EMM provider)"
echo "  □ Managed Google domain (from your customer)"
echo "  □ Test ApplicationId ready"
echo ""

echo "[Step 18.3] End-to-End Testing Steps"
echo "───────────────────────────────────"
echo ""
echo "1. Create Test Application with New ApplicationId"
echo "   - Modify android/app/build.gradle"
echo "   - Change applicationId to com.yourcompany.app.enterprise"
echo "   - Rebuild AAB with new ApplicationId"
echo ""

echo "2. Claim Managed Google Domain"
echo "   - Customer provides managed Google domain"
echo "   - Bind domain to your EMM"
echo "   - Note: If domain already bound, may need to unbind first"
echo ""

echo "3. Publish to Private Channel"
echo "   - Upload app to managed Google Play"
echo "   - Configure as private app for the domain"
echo "   - Set up managed configuration (if needed)"
echo ""

echo "4. Configure via EMM Console"
echo "   - Set up work devices in EMM console"
echo "   - Distribute app to devices"
echo "   - Set managed configuration values"
echo "   - Apply device policies"
echo ""

echo "[Step 18.4] EMM-Specific Configuration"
echo "─────────────────────────────────────"
echo ""
echo "Managed Configuration:"
echo "  - Define in AndroidManifest.xml"
echo "  - Provide default values"
echo "  - Allow EMM to override via console"
echo ""
echo "Device Policies:"
echo "  - Screen capture restrictions"
echo "  - Network policies"
echo "  - App update policies"
echo ""

echo "[Step 18.5] Testing Checklist"
echo "─────────────────────────────"
echo ""
echo "Before finalizing EMM deployment:"
echo "  □ App installs correctly on managed devices"
echo "  □ Managed configuration is applied"
echo "  □ Device policies are enforced"
echo "  □ App updates work correctly"
echo "  □ App removal works correctly"
echo "  □ All features work in managed context"
echo ""

echo "[Step 18.6] EMM Provider Links"
echo "──────────────────────────────"
echo ""
echo "Popular EMM Providers:"
echo "  - Google Workspace (formerly G Suite)"
echo "  - Microsoft Intune"
echo "  - VMware Workspace ONE"
echo "  - MobileIron"
echo "  - IBM MaaS360"
echo ""
echo "Consult your EMM provider's documentation for specific steps."
echo ""

echo "[Step 18] EMM deployment guide complete."

